# Generated by Django 5.2.17 on 2026-09-08 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSnapshot',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('stories', models.JSONField(null=True)),
                ('partial', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(null=True)),
                ('refresh_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('refresh_token', models.UUIDField(null=True)),
            ],
        ),
    ]
