"""
Django settings for byteboard project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured


def environment_bool(name, default=False):
    """Require explicit boolean values instead of trusting non-empty text."""
    value = os.environ.get(name, str(default)).strip().lower()
    if value in {"true", "1"}:
        return True
    if value in {"false", "0"}:
        return False
    raise ImproperlyConfigured(f"{name} must be true, false, 1 or 0.")


def environment_list(name):
    """Read comma-separated hosts or origins without empty entries."""
    return [item.strip() for item in os.environ.get(name, "").split(",")
            if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if os.path.isfile(BASE_DIR / 'env.py'):
    import env


SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured("Set SECRET_KEY in the environment.")

DEBUG = environment_bool("DEBUG")

ALLOWED_HOSTS = environment_list("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = environment_list("CSRF_TRUSTED_ORIGINS")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Enable only behind Heroku's router, which sets X-Forwarded-Proto itself.
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if environment_bool("TRUST_HEROKU_PROXY") else None
)
# Explicit opt-in permits local HTTP checks; production must enable this.
SECURE_SSL_REDIRECT = environment_bool("SECURE_SSL_REDIRECT")
# Choose an HSTS policy only after the final domain and HTTPS are verified.
SECURE_HSTS_SECONDS = 0


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'news',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'byteboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'byteboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_PATH', BASE_DIR / 'db.sqlite3'),
    }
}


if os.environ.get("DATABASE_URL"):
    try:
        database = dj_database_url.parse(
            os.environ["DATABASE_URL"],
            conn_max_age=60,
            conn_health_checks=True,
            ssl_require=environment_bool("DATABASE_SSL_REQUIRE"),
        )
        if database["ENGINE"] != "django.db.backends.postgresql":
            raise ValueError("Unsupported database")
    except (ValueError, KeyError):
        raise ImproperlyConfigured(
            "DATABASE_URL must be a PostgreSQL URL."
        ) from None
    database.setdefault("OPTIONS", {})["connect_timeout"] = 5
    DATABASES["default"] = database


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'news:home'
LOGOUT_REDIRECT_URL = 'news:home'

# Official Hacker News API integration
HACKER_NEWS_API_BASE_URL = 'https://hacker-news.firebaseio.com/v0'
HACKER_NEWS_STORY_LIMIT = 30
HACKER_NEWS_CACHE_TIMEOUT = 60
HACKER_NEWS_REQUEST_TIMEOUT = 5
HACKER_NEWS_REFRESH_BUDGET = 10
HACKER_NEWS_MAX_WORKERS = 5


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
